# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          config-file: .release-please-config.json # Corrected path
          manifest-file: .release-please-manifest.json # Corrected path

      - name: Setup .NET SDK
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet restore GameEngine.sln

      - name: Build Solution
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet build GameEngine.sln --configuration Release --no-restore

      - name: Pack All NuGet packages with Release Version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          RELEASE_VERSION="${{ steps.release.outputs.version }}"
          echo "Packing NuGet packages with version: $RELEASE_VERSION"
          dotnet pack GameEngine.sln --configuration Release --output .nupkg /p:Version=$RELEASE_VERSION --no-build

      # --- Diagnostic Step: Check GitHub Token Permissions ---
      - name: Check GitHub Token Permissions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Checking permissions for GITHUB_TOKEN..."
          # This command will list the permissions granted to the GITHUB_TOKEN for this workflow run.
          # It requires the GitHub CLI to be available on the runner, which it usually is.
          gh auth status --show-token --hostname github.com
          gh api /user/permissions --jq .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure token is available for gh CLI

      - name: Push All NuGet packages to GitHub Packages
        if: ${{ steps.release.outputs.release_created }}
        # Pass the token via an environment variable for dotnet nuget push
        run: dotnet nuget push .nupkg/*.nupkg --api-key "$GITHUB_TOKEN" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Explicitly make GITHUB_TOKEN available as an env var

      - name: Update GitHub Release Description with Links
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/github-script@v7
        with:
          script: |
            const releaseId = "${{ steps.release.outputs.id }}";
            const releaseHtmlUrl = "${{ steps.release.outputs.html_url }}";
            const currentBody = "${{ steps.release.outputs.body }}" || '';
            
            const REPO_OWNER = context.repo.owner;
            const REPO_NAME = context.repo.repo;
            
            // Define footerContent as a single-line JavaScript string using explicit \n for newlines
            const footerContent = "## Package Links\\n\\n**GitHub Packages:**\\n\\n" +
              "- [GameEngine.AI](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.AI)\\n" +
              "- [GameEngine.Animation](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Animation)\\n" +
              "- [GameEngine.Assets](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Assets)\\n" +
              "- [GameEngine.Audio](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Audio)\\n" +
              "- [GameEngine.Core](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Core)\\n" +
              "- [GameEngine.Input](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Input)\\n" +
              "- [GameEngine.Particles](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Particles)\\n" +
              "- [GameEngine.Physics](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Physics)\\n" +
              "- [GameEngine.Rendering](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Rendering)\\n" +
              "- [GameEngine.SaveLoad](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.SaveLoad)\\n" +
              "- [GameEngine.Scene](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Scene)\\n" +
              "- [GameEngine.State](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.State)\\n" +
              "- [GameEngine.Tiles](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.Tiles)\\n" +
              "- [GameEngine.UI](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEngine.UI)\\n" +
              "- [GameEnginePlayground](https://github.com/" + REPO_OWNER + "/" + REPO_NAME + "/packages/GameEnginePlayground)\\n\\n" +
              "**Direct Downloads (Release Assets):**\\n\\n" +
              "- [View Source Code Assets for this Release](" + releaseHtmlUrl + "#assets)\\n";
            
            const newBody = currentBody + '\n\n' + footerContent;
            
            console.log(`Updating release ${releaseId} with new body...`);
            
            try {
              await github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: releaseId,
                body: newBody
              });
              console.log(`Successfully updated release ${releaseId} description.`);
            } catch (error) {
              console.error(`Failed to update release ${releaseId}: ${error.message}`);
              core.setFailed(`Failed to update release ${releaseId}: ${error.message}`);
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
