# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          # --- CRITICAL CHANGE HERE ---
          # Use the config-file instead of individual parameters
          config-file: ./.release-please-config.json # <--- Point to your new config file
          # Remove 'release-type', 'path', 'manifest-file' from here, they are in the config-file
          # release-type: simple
          # path: CHANGELOG.md
          # manifest-file: Directory.Build.props