# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        # --- CRITICAL CHANGE HERE ---
        # Use the explicit latest tag shown in the image
        uses: googleapis/release-please-action@v4.2.0 # Changed to v4.2.0
        id: release
        with:
          release-type: simple
          changelog-path: CHANGELOG.md
          manifest-file: GameEngine.sln # Ensure this path is correct