# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write # <--- CRITICAL: ADD THIS LINE FOR GITHUB PACKAGES

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          config-file: .release-please-config.json # <--- Ensure the dot is there if file is in root
          manifest-file: .release-please-manifest.json # <--- Ensure the dot is there if file is in root

      # --- GitHub Packages Publishing Steps (Conditional) ---
      - name: Setup .NET SDK
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify your .NET SDK version
          # Configure GitHub Packages as a NuGet source
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          # The 'nuget-token' input is not used in v4. We provide the token via env.
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # <--- CORRECTED ENV VARIABLE NAME

      - name: Restore dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet restore GameEngine.Engine/GameEngine.Engine.csproj # <--- TARGET THE NEW BUNDLE PROJECT

      - name: Build Main Project (to trigger Fody weaving)
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet build GameEngine.Engine/GameEngine.Engine.csproj --configuration Release --no-restore
        # CRITICAL: TARGET THE NEW BUNDLE PROJECT HERE

      - name: Pack Main NuGet package
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet pack GameEngine.Engine/GameEngine.Engine.csproj --configuration Release --output .nupkg --no-build
        # CRITICAL: TARGET THE NEW BUNDLE PROJECT HERE.

      - name: Push NuGet package to GitHub Packages
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet nuget push .nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate