# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: googleapis/release-please-action@v4.2.0 # Confirmed correct version
        id: release
        with:
          release-type: simple
          path: CHANGELOG.md
          # Use Directory.Build.props as the manifest file
          manifest-file: Directory.Build.props # <--- Ensure this path is correct and file exists