# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write # Crucial for GitHub Packages

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      # --- GitHub Packages Publishing Steps (Conditional) ---
      - name: Setup .NET SDK
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify your .NET SDK version
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        if: ${{ steps.release.outputs.release_created }}
        # Restore the entire solution
        run: dotnet restore GameEngine.sln

      - name: Build Solution
        if: ${{ steps.release.outputs.release_created }}
        # Build the entire solution to ensure all projects are compiled
        run: dotnet build GameEngine.sln --configuration Release --no-restore

      - name: Pack All NuGet packages
        if: ${{ steps.release.outputs.release_created }}
        # Pack all packable projects in the solution
        run: dotnet pack GameEngine.sln --configuration Release --output .nupkg --no-build
        # This will create a .nupkg file for each project with IsPackable=true

      - name: Push All NuGet packages to GitHub Packages
        if: ${{ steps.release.outputs.release_created }}
        # Push all .nupkg files found in the output directory
        run: dotnet nuget push .nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate